---
title: "Exercise for Session2: Hypothesis Testing and ANOVA"
author: "MRC London Institute of Medical Sciences (http://bioinformatics.lms.mrc.ac.uk)"
date: "25/Sep/2019"
output: html_document
---

These exercises cover the sections of Statistics in R [Session2: Hypothesis Testing and ANOVA]("../CBW_StatisticsInR_course.html#/54").

**Exercise 1**

- Read in the file categoriesAndExpression.txt.
- How many genes are in `ofInterest` and how many gene are in `pathways`.
- What are the quantiles of overall `Expression`, and in `Glycolysis` genes and in `TGFb` genes.
- How many genes were `selected` and in the `Glycolysis` pathway.
- Given a normal distibution for the data, what is the probablity of selecting a gene with at least the expression level of `"Gene13"`
- Perform a t-test to evaluate the difference of the `Expression` levels between genes in the `Glycolysis` pathway and genes in the `TGFb` pathway.

**Exercise 2**

- Read in the file that we used for the Session 1 exercise `data/Life_expectancy_at_birth.csv`.
- Perform an ANOVA analysis and see whether the mean of life expectancy differs across different areas in the UK.
- If the mean of life expectancy differs across different areas in the UK, perform the post-hoc analysis using `TukeyHSD()`.


```{r,echo=F}
Life_exp<-read.csv("../data/Life_expectancy_at_birth.csv",header=T)
boxplot(life.expectancy~area,data=Life_exp,las=2, cex.axis=0.6)
```


